package comparisonOperator
 
import com.jef.entity.ComparisonOperatorEntity
 
/**
 * 当前规则用于测试drools提供的操作运算符
 */
 
// 测试比较操作符contains
rule "rule_comparison_contains"
    when
        ComparisonOperatorEntity(name contains "Jef") or
        ComparisonOperatorEntity(list contains name)
    then
        System.out.println("规则：rule_comparison_contains触发了...");
end
 
// 测试比较操作符contains
rule "rule_comparison_not_contains"
    when
        ComparisonOperatorEntity(name not contains "Jef") and
        ComparisonOperatorEntity(list not contains name)
    then
        System.out.println("规则：rule_comparison_not_contains触发了...");
end
 
// 测试比较操作符memberOf
rule "rule_comparison_memberOf"
    when
        ComparisonOperatorEntity(name memberOf list)
    then
        System.out.println("规则：rule_comparison_memberOf触发了...");
end
 
// 测试比较操作符not memberOf
rule "rule_comparison_not_memberOf"
    when
        ComparisonOperatorEntity(name not memberOf list)
    then
        System.out.println("规则：rule_comparison_not_memberOf触发了...");
end
 
// 测试比较操作符matches
rule "rule_comparison_matches"
    when
        ComparisonOperatorEntity(name matches "Jef*") // 正则表达式
    then
        System.out.println("规则：rule_comparison_matches触发了...");
end
 
// 测试比较操作符not matches
rule "rule_comparison_not_matches"
    when
        ComparisonOperatorEntity(name not matches "Jef*") // 正则表达式
    then
        System.out.println("规则：rule_comparison_not_matches触发了...");
end